const test = require('tape');
const dateFormat = require('dateformat');
const quiz = require('../lib/quiz');
var nock = require('nock');
const config = require('../config');

// Dummy data used for Mocks
let source = 1;
let destination = 2;
let id = 3;
let courseid = 4;
let quizid = 5;
let nameresponse = 'Canvas API - Test Suite quiz';
let res;

// Mock http calls

res = nock('https://'+config.domain+'/api/'+config.apiVersion)
  .post('/courses/'+courseid+'/quizzes')
  .reply(200, { id: id });


  res = nock('https://'+config.domain+'/api/'+config.apiVersion)
  .put('/courses/'+courseid+'/quizzes/'+quizid)
  .reply(200, { name: nameresponse});


  res = nock('https://'+config.domain+'/api/'+config.apiVersion)
  .get('/courses/'+courseid+'/quizzes/'+quizid)
  .reply(200, { name: nameresponse});


  res = nock('https://'+config.domain+'/api/'+config.apiVersion)
  .intercept('/courses/'+courseid+'/quizzes/'+quizid,'DELETE')
  .reply(200, { id: id });



let now = new Date();
let createParams = {
  quiz: {
    name: 'Canvas API - Test Suite quiz',
    due_at: dateFormat(now.setDate(now.getDate() + 7), 'isoUtcDateTime'),
    lock_at: dateFormat(now, 'isoUtcDateTime'),
    unlock_at: dateFormat(now.setDate(now.getDate() + 1), 'isoUtcDateTime'),
    description: '<p>This is an example quiz generated by the <strong>canvas-api</strong> module, which has now been edited.</p><p>For more information, please visit: <a href="https://www.npmjs.com/package/canvas-api"target="_blank">https://www.npmjs.com/package/canvas-api</a></p>'
  }
};
let editParams = {
  quiz: {
    name: 'Canvas API - Test Suite quiz (Edited)',
    description: 'This is an example quiz generated by the canvas-api module, which has now been edited.'
  }
};

test('quiz - Create', (t) => {
  t.plan(1);
  quiz.create(courseid, createParams, (error, results) => {
    if (error) {
      t.fail(error.statusCode);
    } else {
      id = results.body.id;
      t.ok(typeof results.body.id, 'number');
    }
  });
});

test('quiz - Edit', (t) => {
  t.plan(1);
  quiz.edit(courseid, quizid, editParams, (error, results) => {
    if (error) {
      t.fail(error.statusCode);
    } else {
      t.ok(results.body.name, editParams.quiz.name);
    }
  });
});

test('quiz - Get', (t) => {
  t.plan(1);
  quiz.get(courseid, quizid, (error, results) => {
    if (error) {
      t.fail(error.statusCode);
    } else {
      t.ok(results.body.name, editParams.quiz.name);
    }
  });
});

test('quiz - Delete', (t) => {
  t.plan(1);
  quiz.delete(courseid, quizid, (error, results) => {
    if (error) {
      t.fail(error.statusCode);
    } else {
      t.ok(typeof results.body.id, id);
    }
  });
});
